haw/haw/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('haw_book_manage.urls')),
]

haw/haw_book_manage/urls.py
from django.urls import path
from . import views

app_name = 'haw'
urlpatterns = [
    path('', views.top, name='top'),
    path('create', views.create, name='create'),
    path('update/<int:book_id>', views.update, name='update'),
    path('delete/<int:book_id>', views.delete, name='delete'),
]

haw/haw_book_manage/models.py
from django.db import models
from django.utils import timezone


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=50)
    publisher = models.CharField(max_length=50)
    finished_date = models.DateField(default=timezone.now)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

haw/haw_book_manage/views/create.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.utils import timezone
from ..models import Book


def create(request):
    template_name = 'create.html'

    if not request.POST:
        return render(request, template_name)
    else:
        tb = Book(
            title=request.POST['title'],
            author=request.POST['author'],
            publisher=request.POST['publisher'],
            finished_date=request.POST['finished_date'],
            created_at=timezone.now(),
            updated_at=timezone.now()
        )

        try:
            tb.save()
        except Exception:
            messages.error(request, f'登録に失敗しました')
            redirect('haw:top')

        return redirect('haw:top')

haw/haw_book_manage/views/delete.py
from django.contrib import messages
from django.shortcuts import redirect
from ..models import Book


def delete(request, book_id):
    tb = Book.objects.get(id=book_id)

    try:
        tb.delete()
    except Exception:
        messages.error(request, f'更新に失敗しました')
        redirect('haw:top')

    return redirect('haw:top')

haw/haw_book_manage/views/top.py
from django.shortcuts import render
from ..models import Book


def top(request):
    template_name = 'top.html'
    book_list = list(Book.objects.all().values())
    books = {'books': book_list}

    return render(request, template_name, books)

haw/haw_book_manage/views/update.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.utils import timezone
from ..models import Book


def update(request, book_id):
    template_name = 'update.html'

    if request.method == 'GET':
        bt = Book.objects.values(
            'id',
            'title',
            'author',
            'publisher',
            'finished_date'
        ).get(id=book_id)
        return render(request, template_name, bt)
    elif request.method == 'POST':
        update_bt = Book.objects.get(id=book_id)
        update_bt.title = request.POST['title']
        update_bt.author = request.POST['author']
        update_bt.publisher = request.POST['publisher']
        update_bt.finished_date = request.POST['finished_date']
        update_bt.updated_at = timezone.now()

        try:
            update_bt.save()
        except Exception:
            messages.error(request, f'更新に失敗しました')
            redirect('haw:top')

        return redirect('haw:top')

haw/haw_book_manage/templates/create.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/redmond/jquery-ui.css">
        <link rel="stylesheet" href="{% static 'css/common.css' %}">
        <link rel="stylesheet" href="{% static 'css/create.css' %}">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
        <title>書籍登録画面</title>
    </head>
    <body>
        <form id="input_book_data" method="post" action="">{% csrf_token %}
            <div class="cp_iptxt">
                <label class="ef">
                    <input type="text" name="title" placeholder="書籍名" pattern=".*\S+.*" title="空白文字は許可されていません" required/>
                </label>
            </div>
            <div class="cp_iptxt">
                <label class="ef">
                    <input type="text" name="author" placeholder="著者" pattern=".*\S+.*" title="空白文字は許可されていません" required/>
                </label>
            </div>
            <div class="cp_iptxt">
                <label class="ef">
                    <input type="text" name="publisher" placeholder="出版社" pattern=".*\S+.*" title="空白文字は許可されていません" required/>
                </label>
            </div>
            <div class="cp_iptxt">
                <label class="ef">
                    <input id="finish_date" type="text" name="finished_date" placeholder="読了日" required/>
                </label>
            </div>
            <br>
            <button id="create" type="submit" class="action-button">登録</button>
        </form>
    </body>
    <script src="{% static 'js/common.js' %}"></script>
    <script src="{% static 'js/datepicker-ja.js' %}"></script>
</html>

haw/haw_book_manage/templates/top.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="{% static 'css/common.css' %}">
        <title>書籍一覧画面</title>
    </head>
    <body>
        <a href="{% url 'haw:create' %}"><input id="create" type="button" value="追加" class="action-button"></a>
        {% if messages %}
            {% for message in messages %}
                <a style="color: red">{{ message }}</a>
            {% endfor %}
        {% endif %}
        <table>
            <tr>
                <th>書籍名</th>
                <th>著者</th>
                <th>出版社</th>
                <th>読了日</th>
                <th></th>
                <th></th>
            </tr>
            {% for book in books %}
                <tr id="book_{{ book.id }}">
                    <td>{{ book.title }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.publisher }}</td>
                    <td>{{ book.finished_date }}</td>
                    <td><form action="{% url 'haw:update' book.id %}" method="get">
                        <input id="update" type="submit" value="更新" class="action-button"></form>
                    </td>
                    <td><form action="{% url 'haw:delete' book.id %}" method="post">{% csrf_token %}
                        <input id="delete" type="submit" value="削除" class="action-button"></form>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </body>
</html>

haw/haw_book_manage/templates/update.html
    {% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/redmond/jquery-ui.css">
        <link rel="stylesheet" href="{% static 'css/common.css' %}">
        <link rel="stylesheet" href="{% static 'css/create.css' %}">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
        <title>書籍更新画面</title>
    </head>
    <body>
        <form id="input_book_data" method="post" action="">{% csrf_token %}
            <div class="cp_iptxt">
                <label class="ef">
                    <input type="text" name="title" placeholder="書籍名" value="{{ title }}" pattern=".*\S+.*" title="空白文字は許可されていません" required/>
                </label>
            </div>
            <div class="cp_iptxt">
                <label class="ef">
                    <input type="text" name="author" placeholder="著者" value="{{ author }}" pattern=".*\S+.*" title="空白文字は許可されていません" required/>
                </label>
            </div>
            <div class="cp_iptxt">
                <label class="ef">
                    <input type="text" name="publisher" placeholder="出版社" value="{{ publisher }}" pattern=".*\S+.*" title="空白文字は許可されていません" required/>
                </label>
            </div>
            <div class="cp_iptxt">
                <label class="ef">
                    <input id="set_finished_date" type="text" name="finished_date" value="{{ finished_date|date:'Y-m-d' }}" placeholder="読了日" required/>
                </label>
            </div>
            <br>
            <button id="update" type="submit" class="action-button">更新</button>
        </form>
    </body>
    <script src="{% static 'js/update.js' %}"></script>
    <script src="{% static 'js/datepicker-ja.js' %}"></script>
</html>